#M20A28 boiler plate
name: Deploy To Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

  
