#M20A28 boiler plate
name: Checking Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Checking Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run:  |
          npm install
          cd server && npm install
          cd ../client && npm install

      - name: Install Cypress globally
        run: npm install --location=global cypress

      - name: Verify Cypress
        run: cypress verify

      - name: Run Cypress tests
        run: cypress run --browser electron